"""add transcript field to recipes

Revision ID: f5db9b27167f
Revises: bf198ec30d32
Create Date: 2026-03-13 23:21:45.070231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5db9b27167f'
down_revision: Union[str, None] = 'bf198ec30d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'transcript')
    # ### end Alembic commands ###
