"""add video_timestamp_seconds to steps

Revision ID: 5ddd8579f231
Revises: 3a4d62542952
Create Date: 2026-03-16 22:56:56.570106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddd8579f231'
down_revision: Union[str, None] = '3a4d62542952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pantry_owner_name', table_name='pantry_items')
    op.add_column('steps', sa.Column('video_timestamp_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'video_timestamp_seconds')
    op.create_index('ix_pantry_owner_name', 'pantry_items', ['owner_id', 'normalized_name'], unique=False)
    # ### end Alembic commands ###
